# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('bank', models.CharField(max_length=128)),
                ('account', models.CharField(max_length=128)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                          '+63xxxxxxxxxx'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('primary_address', models.CharField(blank=True, max_length=2048)),
                ('alternate_address', models.CharField(blank=True, max_length=2048)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=128, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True)),
                ('promo', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('next_due_date', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, null=True, unique=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.CharField(max_length=256, null=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.Cube')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bank', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_app.Bank')),
                ('merchant', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=7)),
                ('net', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payout', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
