# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='alternate_address',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                                          '+63xxxxxxxxxx'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='primary_address',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='cube',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cube',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cube',
            name='promo',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cube',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_app.Cube'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='gross',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='net',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
