# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_auto_20170729_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
