# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_auto_20170729_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='reference_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='remarks',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
