# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0005_auto_20170801_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
