# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_app', '0007_auto_20170801_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(null=True)),
                ('subject', models.CharField(max_length=128, null=True)),
                ('detail', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('merchant_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cube',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cube',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
